

CREATE TABLE Users(
Name VARCHAR (60) NOT NULL,
USER_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
EMAIL VARCHAR(250) UNIQUE NOT NULL,
PASSWORD VARCHAR (250) NOT NULL,
CREATED_ON TIMESTAMP
);
CREATE TABLE boards (
    board_id SERIAL PRIMARY KEY,          
    title VARCHAR(250) NOT NULL,
    user_id UUID REFERENCES users(user_id) ON DELETE CASCADE, 
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE PIN(
P_ID SERIAL PRIMARY KEY,
title varchar(250) not null,
description varchar(500),
tags varchar (250),
user_id UUID REFERENCES users(user_id) ON DELETE CASCADE,
created_on TIMESTAMP Default CURRENT_TIMESTAMP
);
ALTER TABLE PIN
ADD COLUMN PIN_URL TEXT NOT NULL;
CREATE TABLE pin_board (
    pin_id INTEGER REFERENCES pin(p_id) ON DELETE CASCADE,
    board_id INTEGER REFERENCES boards(board_id) ON DELETE CASCADE,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (pin_id, board_id) 
);
CREATE TABLE category (
    c_id SERIAL PRIMARY KEY,
    title VARCHAR(250) UNIQUE NOT NULL,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE pin_category (
    c_id INTEGER REFERENCES category(c_id) ON DELETE CASCADE,
    pin_id INTEGER REFERENCES pin(p_id) ON DELETE CASCADE,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (c_id, pin_id) 
);